services:
  server:
    restart: always
    expose:
      - 3000
    command: ['yarn', 'start']
    build:
      context: ./
    environment:
      - PORT=3000
      # - NODE_ENV=production
    volumes:
      - './:/workspace'
      - './:/workspace/node_modules'
    ports:
      - 3000:3000