version: '3'
services:
  nginx:
    image: nginx
    restart: always
    command: ['yarn', 'start']
    volumes:
      - './:/workspace'
      - './:/workspace/node_modules'
    depends_on:
      - website1
      - website2
      - website3
    ports:
      - 8888:80
  website1:
    build: ./
    environment:
      - PORT=3000
  # server:
  #   restart: always
  #   expose:
  #     - 3000
  #   command: ['yarn', 'start']
  #   build:
  #     context: ./
  #   environment:
  #     - PORT=3000
  #     # - NODE_ENV=production
  #   volumes:
  #     - './:/workspace'
  #     - './:/workspace/node_modules'
  #   ports:
  #     - 3000:3000