// Rec Detail
export const FETCH_REC_DETAIL_PRODLIST = 'FETCH_REC_DETAIL_PRODLIST';
export const FETCH_REC_DETAIL_PRODLIST_SUCCESS =
    'FETCH_REC_DETAIL_PRODLIST_SUCCESS';
export const UPDATE_REC_DETAIL_DATA = 'UPDATE_REC_DETAIL_DATA';
export const POST_REC_DETAIL_DATA = 'POST_REC_DETAIL_DATA';
export const POST_REC_DETAIL_DATA_SUCCESS = 'POST_REC_DETAIL_DATA_SUCCESS';
export const RESET_REC_DETAIL_RESULT = 'RESET_REC_DETAIL_RESULT';
